// angular-website/src/app/components/button/button.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-button',
  templateUrl: './button.component.html',
  styleUrls: ['./button.component.scss']
})
export class ButtonComponent {
  @Input() buttonText: string = '';

  logMessage() {
    console.log("I hope you like the look of the webpage! \nCheck it out in smaller screen sizes as well :)");
  }
}

<button 
    class="my-button"
    (click)="logMessage()">
    {{buttonText}}
</button>

// react-website/src/components/Button/Button.jsx
import './Button.css'

export function Button({buttonText}) {
    function logMessage() {
        console.log("I hope you like the look of the webpage! \nCheck it out in smaller screen sizes as well :)");
    }

    return (
        <button 
            onClick={logMessage}
            className="my-button">
            {buttonText}
        </button>
    )
}
